data:
    mode: raw
    num_particles: 50
    rounded: false
checkpointing:
    checkpoint_path: /home/yhuang2/PROJs/RealTimeAlignment/train/mlp_v2/checkpoints-3_3/
    save_frequency: 10
    resume: true
model:
    in_features: 6
    out_features: 27
    embedding_features: [512, 256]
    subset_config:
        - [3, 512, 256]
        - [3, 512, 256]
    randperm: true
    batchnorm: false
    activ:
        name: leakyrelu
        negative_slope: .1
    rezero: true
train:
    num_epochs: 200
    num_warmup_epochs: 50
    batch_size: 32
    learning_rate: 0.0001
    sched_steps: 20
    sched_gamma: .95
